### ISSUE TITLE
Add documentation for a few variables

### ISSUE THREAD

**Issue by hjohns12** [uclalawcovid19behindbars/data#15]
- `Description`
- `Different.Operator`
- `Security`

**Comment by nmmarquez** [comment]
Adding here that we should also update the documentation to correctly describe `Residents.Tadmin` as well as vaccination variables
- `Residents.Initiated`
- `Residents.Completed`
- `Residents.Vadmin`
- `Staff.Initiated`
- `Staff.Completed`
- `Staff.Vadmin`

**Comment by hjohns12** [comment]
Noting that these changes need to happen in the historical data repo as well

**Comment by hjohns12** [comment]
Adding a few more! Waiting to add this documentation until we add them to the GitHub // google sheet.

* `Residents.Population`
* `Residents.Tested`
