### ISSUE TITLE
Adding new scraped data 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/data#20]
I think this is the exhaustive list of steps for this process: 

- [x] Check with CDC and Hyperobjekt to avoid breaking things 
- [x] Update `write_latest_data` with the new file path 
- [x] Update `write_latest_data` to select the following additional variables: `Population.Feb20`, `Residents.Population`, `Residents.Tested`, `Residents.Initiated`, `Residents.Completed`, `Residents.Vadmin`, `Staff.Initiated`, `Staff.Completed`, `Staff.Vadmin`
- [x] Update the Google Sheet with the new file path 
- [x] Update the Google Sheet to include headers for the new variables 
- [x] Update the data repository documentation with the new variables

**Comment by hjohns12** [comment]
Just noting that documentation issues have been made:

https://github.com/uclalawcovid19behindbars/data/issues/15 

https://github.com/uclalawcovid19behindbars/data/issues/14
