### ISSUE TITLE
Irregular drop in # of deaths from June 2021

### ISSUE THREAD

**Issue by hjohns12** [uclalawcovid19behindbars/data#27]
I noticed that between June 20th and June 27th, 2021, the number of deaths among incarcerated people on the "state prison" level dropped by ~400. I would like to understand and document where this is coming from. If useful, I wrote [one quick script](https://github.com/uclalawcovid19behindbars/data-viz/blob/master/ad-hoc/deaths_calc.R) to identify the issue.

**Comment by hjohns12** [comment]
More info! The following 21 states have drops in the number of deaths by the same amount on both 6/20/21 and 6/27/21: 

Alaska, Colorado, Connecticut, Georgia, Hawaii, Iowa, Louisiana, Massachusetts, Minnesota, Montana, New Hampshire, New Mexico, North Dakota, Oklahoma, Oregon, Rhode Island, South Dakota, Utah, Washington, Wyoming

Vermont is an exception in that it only has a drop on 6/20/21 rather than both dates.

Since we're seeing the same drops on both dates, this seems to be a scraping or data aggregation issue on our end rather than a data reporting problem.

**Comment by hjohns12** [comment]
Notes from today~~

1. @ssciolist and I noticed that when we run [this line](https://github.com/uclalawcovid19behindbars/data-viz/blob/8791f70f412d35a2f9066ae26cd3f60d884bbedf/ad-hoc/deaths_calc.R#L19), there is a ~400 count drop in the number of deaths. When we try to look at the data on the state-level, [here](https://github.com/uclalawcovid19behindbars/data-viz/blob/8791f70f412d35a2f9066ae26cd3f60d884bbedf/ad-hoc/deaths_calc.R#L38), we cannot isolate the state/s where the drops are coming from. CONFUSING TO SAY THE LEAST!

2. Looking at the data aggregated at the `Web.Group` level, the drop in deaths issue seems to have gotten "fixed" by September 5th. Some ideas for next steps: 

- [ ] Look at [`alt_aggregate_counts()`](https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/alt_aggregate_counts.R) change-log between June 15 and September 5th to check out any changes that might be driving this drop. 
- [ ] Look at [`write_state_jurisdiction_data()`](https://github.com/uclalawcovid19behindbars/covid19_behind_bars_scrapers/blob/9607e5a3343fcb6b5d4d4dc2e1b3338f48ce6591/R/utilities.R#L720) change-log in the same time frame to see if the way we wrote state_jur_counts dataset shifted in this period
- [x] Read data team meeting notes from this time range to check for changes discussed

**Comment by ssciolist** [comment]
Brain dump:
The first drop comes on 6/27/21, a Sunday. The way I understand that our data aggregates to the week, this means that the code change came sometime that week, 6/27 - 7/3
[7/2/21](https://github.com/uclalawcovid19behindbars/data/commit/5f0f13a4546442c4f00f67a4ae42baefb7ab015f): First scraper run to include a latest-data/state_jurisdiction_aggregate_counts.csv file. ([Compare to 6/28 run](https://github.com/uclalawcovid19behindbars/data/commit/1a058386616adbc26403d48a252c1a2c509c53ee))
6/30 - [two days earlier,](https://github.com/uclalawcovid19behindbars/covid19_behind_bars_scrapers/commit/5aa4a450c70fb852062e083eaebe807796e64695) update to write state-jurisdiction aggregated file, using alt_aggregate_counts

Then, there's later a big jump of 241 deaths from 8/29 to 9/5. Again, thinking about the way that our data aggregates to the week, that means the code change that would have "corrected" for the jump would have happened on the week of 9/5 - 9/11.

9/7 - [state prison aggregate fixes](https://github.com/uclalawcovid19behindbars/behindbarstools/pull/130)

What I don't understand is why the historical data from before 6/20 would have been fine. Idk, this one has got me turned around!!

**Comment by hjohns12** [comment]
On June 20th, we lost death data from three states, which amounts to 413 deaths total: 
- Texas (273 deaths) 
- Illinois (88 deaths) 
- Arkansas (52 deaths) 

In this image, the value displayed on the y-axis is the number of scraped deaths.
<img width="905" alt="Screen Shot 2022-04-05 at 19 30 44" src="https://user-images.githubusercontent.com/23141035/161869611-00751427-f028-4743-a73e-bf8aaa4b8239.png">

The "higher ever cumulative count" data feature should resolve this problem, which is neat! 

One note on Texas: The deaths data comes back on September 5th, 2021 at 292. In order to bridge this ~2 month gap, we might use [historical TJI data ](https://docs.google.com/spreadsheets/d/1mOS1wggvyRUOpI-u2VabmnQ1yJPPEgOc2zdZjWxbAwQ/edit). I'll open a new issue to address this possibility.
